const challenges1 = [
    {
        id: 'ch_001',
        name: 'Bombs Landed',
        challenge: "This is challenege 1",
        hint: "Computers can't talk us directly.",
        points: 50,
        hint_deduction: 5,
        difficulty: 'easy',
        flag: 'binarycode007',
        category: 'web',
    },
    {
        id: 'ch_002',
        name: 'Bombs Landed',
        challenge: "This is challenege 2",
        hint: "Computers can't talk us directly.",
        points: 50,
        hint_deduction: 5,
        difficulty: 'easy',
        flag: 'binarycode007',
        category: 'reversing',
    },
    {
        id: 'ch_003',
        name: 'Bombs Landed',
        challenge: "This is challenege 3",
        hint: "Computers can't talk us directly.",
        points: 50,
        hint_deduction: 5,
        difficulty: 'easy',
        flag: 'binarycode007',
        category: 'steg',
    },
]
const challenges2 = [
    {
        id: 'ch_001',
        name: 'Bombs Landed',
        challenge: "Can you find the password?",
        hint: "Computers can't talk us directly.",
        points: 50,
        hint_deduction: 5,
        difficulty: 'easy',
        flag: 'binarycode007',
        category: 'pwning',
    },
    {
        id: 'ch_002',
        name: 'Bombs Landed',
        challenge: "Can you find the password?",
        hint: "Computers can't talk us directly.",
        points: 50,
        hint_deduction: 5,
        difficulty: 'easy',
        flag: 'binarycode007',
        category: 'machine',
    },
]
const challenges3 = [
    {
        id: 'ch_001',
        name: 'Bombs Landed',
        challenge: "Can you find the password?",
        hint: "Computers can't talk us directly.",
        points: 50,
        hint_deduction: 5,
        difficulty: 'easy',
        flag: 'binarycode007',
        category: 'misc',
    },
]

const strings = [
    "Initialzing request",
    "Resolving internet address 127.0.0.1",
    "Requesting access to server",
    "Entering credentials",
    "Login denied",
    "Re-entering credentials",
    "Access granted",
    "Finding CTF backend services",
    "Services found on port 80",
    "Starting mcstausd",
    "Starting portmap",
    "Starting setroubleshootd",
    "Starting RPC idmapd",
    "Starting mdmonitor",
    "Starting system message bus",
    "Starting Bluetooth services",
    "Starting other filesystems",
    "Starting PC/SC smart card daemon (pcscd)",
    "Starting hidd",
    "Enabling /etc/fstab swaps",
    "INIT: Entering runlevel 3",
    "Entering non-interactive startup",
    "Applying INTEL CPU microcode update",
    "Checking for hardware changes",
    "Bringing up interface eth0",
    "Determining IP information for eth0... done.",
    "Starting mcstausd",
    "Starting portmap",
    "Starting setroubleshootd",
    "Starting RPC idmapd",
    "Starting mdmonitor",
    "Starting system message bus",
    "Starting Bluetooth services",
    "Starting other filesystems",
    "Starting PC/SC smart card daemon (pcscd)",
    "Starting hidd",
    "Enabling /etc/fstab swaps",
    "INIT: Entering runlevel 3",
    "Entering non-interactive startup",
    "Applying INTEL CPU microcode update",
    "Checking for hardware changes",
    "Bringing up interface eth0",
    "Determining IP information for eth0... done.",
    "Connecting to backend service",
    "Connected to backend service",
    "Finding CTF database services",
    "Services found on port 3306",
    "Establishing connection to the database",
    "Connection established",
    "Logging into the database server",
    "Login successful",
    "Reading database",
    "Fetching data from database",
    "Data acquired",
    "Finding other resources",
    "Fetching resources",
    "Processing DOM",
    "Loading images",
    "Loading content",
    "Page rendered",
    "Starting display manager",
    "WELCOME TO LAKSHYA CTF INC 2020",
    "Initializing..."
  ];
  

export { challenges1, challenges2, challenges3, strings };